function fig = lift()
    rectangle('Position', [0 1 10 4],...
	'FaceColor', 'white');
    text(0,0.9,'1st Floor','Color',[0 0 0]);
    rectangle('Position', [0 1 10 0],...
	'FaceColor', 'white');
    text(0,1.9,'2nd Floor','Color',[0 0 0]);
    rectangle('Position', [0 2 10 0],...
	'FaceColor', 'white');
    rectangle('Position', [0 3 10 0],...
	'FaceColor', 'white');
    text(0,2.9,'3rd Floor','Color',[0 0 0]);
    rectangle('Position', [0 4 10 0],...
	'FaceColor', 'white');
    text(0,3.9,'4th Floor','Color',[0 0 0]);
    fig=rectangle('Position', [4.5 0 1 1],...
	'FaceColor', 'black');
end
