function massH = mk_mass(axesH)
rectangle('Position', [0 0 1.2 1.2],...
        'Curvature', [1 1],...
        'FaceColor','Black');
    rectangle('Position', [0 9 1.2 1.2],...
        'Curvature', [1 1],...
        'FaceColor','Black');
    rectangle('Position', [19 9 1.2 1.2],...
        'Curvature', [1 1],...
        'FaceColor','Black');
    rectangle('Position', [19 0 1.2 1.2],...
        'Curvature', [1 1],...
        'FaceColor','Black');
    massH = rectangle(axesH,...
        'Position', [0 0 1 1],...
        'Curvature', [1 1],...
	'FaceColor', 'Black');
end
